### PR TITLE
Adapt for latest VS2019, which supports "concept".

### PR DESCRIPTION
**Pull request by 7ofNine**
use "/std:c++latest" in order to use/activate it

### CODE REVIEW

**Comment by bluescarni** [comment]
@7ofNine Thanks a lot! This is a very good start.

A couple of comments:

- ``MPP_CONCEPT_DECL`` should be ``MPPP_CONCEPT_DECL``, I guess a typo? Hopefully easy to search & replace.
- You don't need to bother with:

```c++
#if !defined(_MSC_VER)
    explicit integer(const CppInteroperable &x)
#else
    template <CppInteroperable T>
    explicit integer(const T &x)
#endif
```

You can just keep only the MSVC concepts syntax, which should also be supported by the GCC implementation. The syntax:

```c++
 explicit integer(const CppInteroperable &x)
```

is an abbreviated concept declaration, which was present in early revisions of the concepts features but was later dropped.

I think there will be some issues to sort out with the documentation, as I am not sure doxygen will be ok with the updated concepts syntax. But I can fix that in a dedicated PR later (I am planning to drop doxygen altogether eventually).

**Comment by 7ofNine** [comment]
@bluescarni I'll work on it.
Because I typically don't compile using gcc I stayed on the save side but I can change that. What doesn't seem to be in the latest drafts for concept is the use of a constraint as a function parameter. What I found quickly browsing through some of the comments was that syntax doesn't make it clear enough that one is dealing with constraint and not with a type and there seems to be a suggestion to use "auto" with it, nothing final, yet, so it is not in the draft.

B.T.W. with my changes piranha-tng compiles, too, using concepts except for one issue with a friend declaration. For me that looks like a MS issue, but I am not sure, yet, different project anyways.

**Comment by 7ofNine** [comment]
For the documentation: Are you planning to switch over to Sphinx? I could try to get my fingers dirty with it.

**Comment by bluescarni** [comment]
@7ofNine Thanks!

For the docs, currently mp++ uses both doxygen and sphinx. The original idea was to write the documentation in the source code in doxygen markup, and then use a sphinx extension called "breathe" to make the doxygen-generated docs available for use in sphinx:

https://breathe.readthedocs.io/en/latest/

So, the original docs pipeline was:

source code -> doxygen (XML output) -> breathe -> sphinx

For a variety of reasons, this turned out to be working not that great. So recently I have switched to writing docs directly in sphinx.

The problem is that, although all the new docs are being written in pure sphinx, there is a lot of older documentation still written in doxygen format, and that will have to be moved to pure sphinx eventually. So, currently the documentation is in a transition phase between the old doxygen->sphinx pipeline and the new sphinx-only pipeline.

If you feel like helping out with this, that would be really great! In practical terms, the best way to proceed would be to start with those free functions which are still documented in doxygen syntax. E.g., one such example is here:

https://github.com/bluescarni/mppp/blob/master/include/mp%2B%2B/integer.hpp#L7016

The basic idea is to move the existing documentation from the source code to the corresponding sphinx file (``integer.rst``, in this specific case), converting the markup from doxygen to sphinx in the process. In the source code, only a brief one-liner doc blurb would remain, without any special markup.

The next step would be the conversion of the classes documentation. This is slightly more work as it cannot be done member function by member function, the docs for the class and all its member functions have to be converted all in one go.

**Comment by bluescarni** [comment]
I forgot to mention, for the docs we are always adopting the conceptified signatures of functions and classes, which produces leaner, more compact and better-looking documentation.

Sphinx has partial support for documenting C++ concepts, and it most notably does not support ``requires`` clauses. Thus, for those cases in which we have ``requires`` in the function/class signatures, we have to document the requirements in the main body of the function/class documentation.

**Comment by bluescarni** [comment]
@7ofNine I just cleaned up a couple of things, would you mind double-checking that everything still works on the latest MSVC (I don't have access to it)?

**Comment by bluescarni** [comment]
Thanks for tracking this down! Since this seems to be a problem in Boost Multiprecision, and that Boost Multiprecision is used only in the benchmarks (i.e., we don't depend on BMP in the mp++ codebase), I'd be inclined not to do anything about it.

We could in principle add some pragma to shut off the warning, but, as you say, this happens only in debug mode...

**Pull request merged**
