### PR TITLE
Another stab at properly including flint headers.

### PR DESCRIPTION
**Pull request by bluescarni**

### CODE REVIEW

**Comment by bluescarni** [comment]
@7ofNine does this change help with the inclusion of flint headers on your setup?

**Comment by 7ofNine** [comment]
@bluescarni  it didn't work but that is of my own making. I manipulated the cmake of flint to get it installed and that has the effect that all the flint headers are copied into a flat structure, the "include/flint" folder. It works for mp++ without the benchmarks but the benchmarks pull in additional headers and flint itself doesn't like the flat structure. I have to set up a path "include/flintxx and the corresponding headers. Those cmake files (actually just one) is pretty bad and doesn't seem to be used too often. It creates file paths for installation that are simply wrong and don't exist. It uses GLOB which is not recommended at all to maintain the lists of sources etc.  It also doesn't create any projects for profile or tune projects and it creates one single fat project for the library  which makes the build slower than molasses. 
 So leave this branch and I will fix my side for the installation and will try it again. Do you have any idea under which paths and with what folder structure flint is installed in other systems? I don't want to create a structure that contradicts its common use. I don't have access to other installations.

**Comment by bluescarni** [comment]
@7ofNine As far as I can tell, on Unix installations flint installs the headers under ``$PREFIX/include/flint/flint.h`` and Arb under ``$PREFIX/include/arb.h``.

In practical terms, this means something like ``/usr/local/include/flint/flint.h`` and ``/usr/local/include/arb.h``. In other words, flint uses a subdirectory ``flint/`` for its headers, while Arb installs them directly into ``$PREFIX/include`` (which is not that great because Arb's headers are often 3-letters only, thus the probability of name clashes with other libraries is relatively high).

**Comment by bluescarni** [comment]
> So leave this branch and I will fix my side for the installation and will try it again.

You mean to merge the branch or to wait a bit more? I think the branch now does things correctly also from the point of view of Unix installations into arbitrary paths, so I would be inclined to merge it eventually...

**Comment by 7ofNine** [comment]
I mean to wait a bit more until I got the flintxx folder properly installed, which so far only seems to matter for the benchmark tests and merge it after that. Because the integration environment seems to have it correct this is just a local problem on my machine. I could copy it properly by hand but I would like to do it using cmake and verify.

**Comment by bluescarni** [comment]
Ok!

**Comment by 7ofNine** [comment]
I managed to install the flint headers with the correct folder layout. It is .../include/flint/ and .../include/flint/flintxx. This can be determined by the headers *xx.h in the flint folder and "evaluation_tools.h in the flintxx folder. 
But now I run into a problem with compiling the integer1_sort_* and integer2_sort_* benchmark tests. In a template it complains about not being able  to convert type T (looks like const long) into a "const char *". Something I don't understand at all because about a year ago, when I compiled flint for the first time, but did not install it(!!), I could build and run these tests. At that time I used paths directly into the source folder and into the build folder. I have to check a bit further

**Comment by 7ofNine** [comment]
It's loss of memory. I had totally forgotten that I ran into the same problem when I used flint for the first time. It is a constructor in flint that for what ever reason doesn't work when compiled with MSVC when "long" is used. I had set it to "int" and for that case it works fine.

In `auto v = get_init_vector<fmpzxx>(init_time);`

the construction `T(dist(rng))` fials when in dist (uniform distribution) long values are used
i.e. the constructor `fmpzxx(long)` has a problem, while `fmpzxx(int)` works.

**Comment by bluescarni** [comment]
> It's loss of memory. I had totally forgotten that I ran into the same problem when I used flint for the first time. It is a constructor in flint that for what ever reason doesn't work when compiled with MSVC when "long" is used. I had set it to "int" and for that case it works fine.
> 
> In `auto v = get_init_vector<fmpzxx>(init_time);`
> 
> the construction `T(dist(rng))` fials when in dist (uniform distribution) long values are used
> i.e. the constructor `fmpzxx(long)` has a problem, while `fmpzxx(int)` works.

My feeling here is that flint is confused by the fact that ``long`` is 64-bit on Linux while it is 32-bit on Windows, so perhaps the ``fmpzxx`` constructor is not coping well with this difference? What kind of error message are you getting?

**Comment by 7ofNine** [comment]
That's what it is. The construction of a fmpzxx object boils down to the construction of a `    template<class T>
    fmpz_data(const T& t)
    {
        init(t);
    }
`
fmpz_data structure which uses an init method. This method now uses an enabler and/or polymorphism. There are 4 versions of it defined in "fmpzxx.h"
`    void init(const char* str)
    {
        fmpz_init(inner);
        fmpz_set_str(inner, str, 10);
    }
...
    void init(const fmpzxx_srcref& r)
    {
        fmpz_init_set(inner, r._fmpz());
    }
...
    template<class T>
    typename mp::enable_if<traits::is_unsigned_integer<T> >::type init(T t)
    {
        fmpz_init_set_ui(inner, t);
    }
    template<class T>
    typename mp::enable_if<traits::is_signed_integer<T> >::type init(T t)
    {
        fmpz_init(inner);
        fmpz_set_si(inner, t);
    }
`
the last one is the one that is relevant for our case of using "long".
Looking now at the traits (in flint/flintxx/traits.h)
showes.
`// Compute if T belongs to the signed integer types.
template<class T> struct is_signed_integer : false_ { };
template<> struct is_signed_integer<signed char> : true_ { };
template<> struct is_signed_integer<signed short> : true_ { };
template<> struct is_signed_integer<signed int> : true_ { };
template<> struct is_signed_integer<slong> : true_ { };
`
which is distinctly missing "long".
Checking now "slong" in "flint.h" 
`#define slong mp_limb_signed_t
`
mp_limb_signed_t is declared in gmp.h as 

`...
#ifdef _LONG_LONG_LIMB
typedef unsigned long long int	mp_limb_t;
typedef long long int		mp_limb_signed_t;
...
`
i.e. declared as "long long"  because on windows with 64 bit we
have
`#if ! defined (__GMP_WITHIN_CONFIGURE)
#ifdef _WIN32 
#  ifdef _WIN64 
#    define _LONG_LONG_LIMB  1     <<<<<<<<<<<<<<<<<<<<<<<<
#    define GMP_LIMB_BITS   64 
#  else 
#    define GMP_LIMB_BITS   32 
#  endif 
#  define __GMP_BITS_PER_MP_LIMB  GMP_LIMB_BITS 
#  define SIZEOF_MP_LIMB_T (GMP_LIMB_BITS >> 3) 
#  define GMP_NAIL_BITS                       0 
#endif 
`
 In total the init method is not instantiated or any of the other constructor of fmpzxx  if we use "long"

The equivalent same faulty declarations are used when one deals with unsigned. 
When I introduce the enabler with "long" the compilation works. 
I think there is a need for a fix in flintxx.

**Comment by 7ofNine** [comment]
And as I can see the formatting got out of wack. I hope it is still readable. If not i'll can send it in an e-mail

**Comment by bluescarni** [comment]
Yep, sounds about right. Are you using the released version of flint or the latest git? I don't think the flint developers themselves use much the C++ wrappers.

I'll go ahead and merge this PR in the meantime them, if don't have objections.

**Comment by 7ofNine** [comment]
I am using dd1021a6cbaca75d94e6e066c26a3a5622884a7c
from https://github.com/wbhart/flint2/ which is trunk from 2020-02-17 which is probably ahead of the released version 2.5.2 from 2015. The flint documentation says that "slong" is mp_limb_signed_t and represents a long which is clearly not the case. Did gmp change on windows 64 bit?

**Comment by bluescarni** [comment]
> I am using dd1021a6cbaca75d94e6e066c26a3a5622884a7c
> from https://github.com/wbhart/flint2/ which is trunk from 2020-02-17 which is probably ahead of the released version 2.5.2 from 2015. The flint documentation says that "slong" is mp_limb_signed_t and represents a long which is clearly not the case. Did gmp change on windows 64 bit?

I don't think GMP changed anything, they have a fairly strong policy of ABI stability across releases. Perhaps it's a matter of some problem with the ``#ifdefs`` in either GMP or flint under Windows 64-bit? Also, are you using vanilla GMP or mpir?

**Comment by 7ofNine** [comment]
I am using mpir. I'll dig around a little bit and look if there are some changes made in the last 5 years. I just wont get to it today. It could also simply be a bug :-) Because it seems to be contstrained to the benchmarks and I now will **remember** it I am not too affected by it. If I don't find anything it might be worth to create an error report or even a PR. My current work around  wouldn't work in general. It would mess up in other situations, I think.

**Comment by 7ofNine** [comment]
I dug around a little bit and tend to think that the problem is a flintxx problem/bug. Even the original gmp.h does not say that mp_limb_signed_t  is a long. dependending on the situation it is well defined as signed long long. Which means simply that the claim in the flint documentation for slong = mp_limb_signed_t  is long is simply incorrect. 
Personally I don't understand why the enabler is done with slong instead of simply using long and another one with long long. One has to live with both anyways and if something goes wrong this way it has to be corrected. I didn't check but I don't know when  long long was actually introduced. The flintxx interfaces claim to be C98 which might be the cause of the issue.

**Pull request merged**
